# Generated by Django 4.2.5 on 2023-09-18 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='post_id',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
